#!/usr/bin/env python3
"""build_prompts.py — regenerate expert agent prompts from kb/.

Each `kb/<lane>.md` is the source of truth for one expert agent's
knowledge. This script wraps each KB in the shared prompt template
(system instructions + JSON output format) and writes the result to
`agents/expert-<lane>/prompt.md`.

Run any time `kb/*.md` changes:

    python scripts/build_prompts.py

Idempotent — running twice produces identical output. Safe to
re-run in CI as a check that the prompts match the KB.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# (lane name, KB description for system prompt, off-lane examples)
LANES = [
    (
        "scaffold",
        "agent scaffolding",
        "creating new agents, the canonical file layout, agent.yaml fields, "
        "prompt.md templates, JSON Schemas, and validation",
        "deploys or evals",
    ),
    (
        "eval-bench",
        "quality measurement",
        "eval datasets, judges, pass-rate gates, multi-model bench comparison, "
        "and regression detection",
        "scaffolding or deploys",
    ),
    (
        "deploy-ops",
        "deployment and operations",
        "doctor checks, Azure Container Apps deploy, config targets, "
        "submitting jobs, monitoring, notifications",
        "scaffolding or evals",
    ),
]


PROMPT_TEMPLATE = """\
<!-- AUTO-GENERATED from kb/{lane}.md by scripts/build_prompts.py.
     DO NOT EDIT THIS FILE BY HAND — edit kb/{lane}.md and re-run the
     build script. Hand edits will be lost on the next rebuild. -->

You are a movate-cli expert specializing in **{specialty}**:
{topics}.

Answer the user's question using ONLY the knowledge base below. If
the question is outside this lane (e.g. about {off_lane}), say so
honestly and set `confidence` to a low value (≤ 0.3). If the answer
isn't covered in the KB, say "I don't have that in my KB" and return
`confidence: 0.0`.

{kb_body}

# Output format

Return JSON of exactly this shape — no prose, no code fences:

```
{{"answer": "<your answer>", "confidence": <0.0-1.0>}}
```

`confidence` should reflect how well the KB covers the question:
- 0.9+ if the answer is directly in the KB
- 0.6-0.8 if the KB has partial info and you're inferring
- 0.3-0.5 if you're guessing from CLI conventions
- 0.0-0.2 if the question is outside this lane or not in KB

## User question

{{{{ input.question }}}}
"""


def strip_kb_preamble(kb_text: str) -> str:
    """Drop the first ## section's preamble paragraphs that talk about
    'edit this file freely...' — that meta-text is for human readers
    of the kb/ folder, not the LLM."""
    lines = kb_text.splitlines()
    # Find the first H2 line and use everything from there onward.
    # The H1 + intro paragraph are kb/ instructions for humans.
    for i, line in enumerate(lines):
        if line.startswith("## "):
            return "\n".join(lines[i:])
    # Fallback: return as-is if no H2 found.
    return kb_text


def build_prompt(lane: str, specialty: str, topics: str, off_lane: str) -> str:
    kb_path = REPO_ROOT / "kb" / f"{lane}.md"
    if not kb_path.exists():
        sys.exit(f"✗ missing KB file: {kb_path}")
    kb_text = kb_path.read_text().strip()
    kb_body = strip_kb_preamble(kb_text)
    return PROMPT_TEMPLATE.format(
        lane=lane,
        specialty=specialty,
        topics=topics,
        off_lane=off_lane,
        kb_body=kb_body,
    )


def main() -> None:
    written: list[Path] = []
    for lane, specialty, topics, off_lane in LANES:
        prompt = build_prompt(lane, specialty, topics, off_lane)
        out_path = REPO_ROOT / "agents" / f"expert-{lane}" / "prompt.md"
        if not out_path.parent.exists():
            sys.exit(f"✗ missing agent dir: {out_path.parent}")
        out_path.write_text(prompt)
        written.append(out_path)

    print(f"✓ regenerated {len(written)} prompts from kb/:")
    for p in written:
        print(f"   {p.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
